// https://typst.app/universe/package/glossarium

#let glossary = (
  (key: "3gpp", short: "3GPP", long: "3rd Generation Partnership Project"),
  (key: "5qi", short: "5QI", long: "5G QoS Identifier"),
  (key: "bs", short: "BS", long: "Base Station"),
  (key: "bwp", short: "BWP", long: "Bandwidth Part"),
  (key: "cdma", short: "CDMA", long: "Code-Division Multiple Access"),
  (key: "cdrx", short: "C-DRX", long: "Connected Mode DRX"),
  (key: "cp", short: "CP", long: "Cyclic Prefix"),
  (key: "csi-rs", short: "CSI-RS", long: "Channel State Information Reference Signal"),
  (key: "csi", short: "CSI", long: "Channel State Information"),
  (key: "dci", short: "DCI", long: "Downlink Control Information"),
  (key: "dl", short: "DL", long: "Downlink"),
  (key: "drx", short: "DRX", long: "Discontinuous Reception"),
  (key: "fdd", short: "FDD", long: "Frequency-Division Duplexing"),
  (key: "fr", short: "FR", long: "Frequency Range"),
  (key: "harq", short: "HARQ", long: "Hybrid Automatic Repeat Request"),
  (key: "iat", short: "IAT", long: "Inter-Arrival Time"),
  (key: "iid", short: "i.i.d.", long: "independent and identically distributed"),
  (key: "lte", short: "LTE", long: "Long-Term Evolution"),
  (key: "mac", short: "MAC", long: "Medium Access Control"),
  (key: "mcs", short: "MCS", long: "Modulation and Coding Scheme"),
  (key: "mib", short: "MIB", long: "Master Information Block"),
  (key: "mimo", short: "MIMO", long: "Multiple Input, Multiple Output"),
  (key: "mtu", short: "MTU", long: "Maximum Transmission Unit"),
  (key: "nr", short: "NR", long: "New Radio"),
  (key: "nsa", short: "5G NSA", long: "5G Non-Standalone"),
  (key: "ofdm", short: "OFDM", long: "Orthogonal Frequency-Division Multiplexing"),
  (key: "pbch", short: "PBCH", long: "Physical Broadcast Channel"),
  (key: "pcb", short: "PCB", long: "Printed Circuit Board"),
  (key: "pdcch", short: "PDCCH", long: "Physical Downlink Control Channel"),
  (key: "pdsch", short: "PDSCH", long: "Physical Downlink Shared Channel"),
  (key: "poc", short: "PoC", long: "Proof of Concept"),
  (key: "ppo", short: "PPO", long: "Proximal Policy Optimization"),
  (key: "prach", short: "PRACH", long: "Physical Random Access Channel"),
  (key: "pu", short: "PU", long: "Power Unit"),
  (key: "pucch", short: "PUCCH", long: "Physical Uplink Control Channel"),
  (key: "pusch", short: "PUSCH", long: "Physical Uplink Shared Channel"),
  (key: "qam", short: "QAM", long: "Quadrature Amplitude Modulation"),
  (key: "qmi", short: "QMI", long: "Qualcomm Mobile Station Modem Interface"),
  (key: "qoe", short: "QoE", long: "Quality of Experience"),
  (key: "qos", short: "QoS", long: "Quality of Service"),
  (key: "qpsk", short: "QPSK", long: "Quadrature Phase Shift Keying"),
  (key: "ran", short: "RAN", long: "Radio Access Network"),
  (key: "rb", short: "RB", long: "Resource Block"),
  (key: "re", short: "RE", long: "Resource Element"),
  (key: "rf", short: "RF", long: "Radio Frequency"),
  (key: "ric", short: "RIC", long: "RAN Intelligent Controller"),
  (key: "rl", short: "RL", long: "Reinforcement Learning"),
  (key: "rlc", short: "RLC", long: "Radio Link Control"),
  (key: "rnti", short: "RNTI", long: "Radio Network Temporary Identifier"),
  (key: "rrc", short: "RRC", long: "Radio Resource Control"),
  (key: "rrm", short: "RRM", long: "Radio Resource Management"),
  (key: "rsrp", short: "RSRP", long: "Reference Signal Received Power"),
  (key: "rtt", short: "RTT", long: "Round-Trip Time"),
  (key: "rx", short: "Rx", long: "Receive"),
  (key: "sa", short: "5G SA", long: "5G Standalone"),
  (key: "scs", short: "SCS", long: "Subcarrier Spacing"),
  (key: "sib", short: "SIB", long: "System Information Block"),
  (key: "snr", short: "SNR", long: "Signal-to-Noise Ratio"),
  (key: "sr", short: "SR", long: "Scheduling Request"),
  (key: "srs", short: "SRS", long: "Sounding Reference Signal"),
  (key: "ssb", short: "SSB", long: "Signal Synchronization Block"),
  (key: "tcp", short: "TCP", long: "Transmission Control Protocol"),
  (key: "tdd", short: "TDD", long: "Time-Division Duplexing"),
  (key: "tx", short: "Tx", long: "Transmit"),
  (key: "udp", short: "UDP", long: "User Datagram Protocol"),
  (key: "ue", short: "UE", long: "User Equipment"),
  (key: "ul", short: "UL", long: "Uplink"),
  (key: "uml", short: "UML", long: "Unified Modeling Language"),
  (key: "usb", short: "USB", long: "Universal Serial Bus"),
)